"""Curated seed infrastructure projects reflecting real-world MoSPI PAIMANA April 2026 portfolio.

Field names follow the Master Specification Section 3.1 CUF contract
(`expenditure_change_recent`, `progress_change_recent`, `current_delay_months`)
with the full statutory governance trigger set (milestones, clearances,
reporting staleness, dispute status) required by the RuleFloor engine.
"""

from typing import List
from app.paimana_contracts import ProjectInput

MOCK_PAIMANA_PROJECTS: List[ProjectInput] = [
    ProjectInput(
        project_id="MOSPI-RLW-0101",
        project_name="Udhampur-Srinagar-Baramulla Rail Link (USBRL)",
        sector="Railways",
        implementing_agency="Northern Railway / IRCON",
        original_cost=2500.0,
        revised_cost=37012.0,
        expenditure=35200.0,
        expenditure_change_recent=240.0,
        physical_progress=96.5,
        progress_change_recent=0.8,
        original_duration_months=144.0,
        months_elapsed=360.0,
        current_delay_months=216.0,
        overdue_milestones=1,
        total_scheduled_milestones=14,
        clearance_pending_days=45,
        days_since_last_update=12,
        dispute_status="NONE",
        delay_remarks="Final geological strata stabilization in tunnel section pending",
    ),
    ProjectInput(
        project_id="MOSPI-RLW-0194",
        project_name="Western Dedicated Freight Corridor (Dadri to JNPT)",
        sector="Railways",
        implementing_agency="DFCCIL",
        original_cost=28181.0,
        revised_cost=51101.0,
        expenditure=44800.0,
        expenditure_change_recent=410.0,
        physical_progress=88.2,
        progress_change_recent=1.4,
        original_duration_months=144.0,
        months_elapsed=216.0,
        current_delay_months=72.0,
        overdue_milestones=2,
        total_scheduled_milestones=12,
        clearance_pending_days=30,
        days_since_last_update=22,
        dispute_status="CONCILIATION",
        delay_remarks="Utility shifting of transmission line completed in last sector",
    ),
    ProjectInput(
        project_id="MOSPI-RTH-0342",
        project_name="Delhi-Amritsar-Katra Expressway (Package 4)",
        sector="Road Transport & Highways",
        implementing_agency="NHAI",
        original_cost=4200.0,
        revised_cost=4650.0,
        expenditure=2100.0,
        expenditure_change_recent=85.0,
        physical_progress=48.0,
        progress_change_recent=2.1,
        original_duration_months=36.0,
        months_elapsed=24.0,
        current_delay_months=8.0,
        overdue_milestones=2,
        total_scheduled_milestones=10,
        clearance_pending_days=95,
        days_since_last_update=18,
        dispute_status="NONE",
        delay_remarks="Land acquisition compensation disputes with district collector resolved partially",
    ),
    ProjectInput(
        project_id="MOSPI-PWR-0512",
        project_name="Barh Super Thermal Power Project Stage-I (3x660 MW)",
        sector="Power",
        implementing_agency="NTPC",
        original_cost=8692.0,
        revised_cost=16120.0,
        expenditure=15400.0,
        expenditure_change_recent=65.0,
        physical_progress=94.0,
        progress_change_recent=0.5,
        original_duration_months=72.0,
        months_elapsed=192.0,
        current_delay_months=120.0,
        overdue_milestones=3,
        total_scheduled_milestones=12,
        clearance_pending_days=0,
        days_since_last_update=15,
        dispute_status="ARBITRATION",
        delay_remarks="Contractor arbitration on boiler erection claim under tribunal review",
    ),
    ProjectInput(
        project_id="MOSPI-PET-0220",
        project_name="Barmer Petroleum Refinery and Petrochemical Complex",
        sector="Petroleum & Natural Gas",
        implementing_agency="HPCL Rajasthan Refinery Ltd (HRRL)",
        original_cost=43129.0,
        revised_cost=72937.0,
        expenditure=52100.0,
        expenditure_change_recent=650.0,
        physical_progress=76.4,
        progress_change_recent=1.9,
        original_duration_months=48.0,
        months_elapsed=84.0,
        current_delay_months=36.0,
        overdue_milestones=2,
        total_scheduled_milestones=10,
        clearance_pending_days=60,
        days_since_last_update=20,
        dispute_status="NONE",
        delay_remarks="Crude procurement logistics normalized after monsoon disruption",
    ),
    ProjectInput(
        project_id="MOSPI-URB-0418",
        project_name="Bengaluru Metro Rail Project Phase 2A (Silk Board to KR Puram)",
        sector="Urban Development",
        implementing_agency="BMRCL",
        original_cost=5994.0,
        revised_cost=6200.0,
        expenditure=2850.0,
        expenditure_change_recent=110.0,
        physical_progress=42.0,
        progress_change_recent=1.1,
        original_duration_months=60.0,
        months_elapsed=74.0,
        current_delay_months=14.0,
        overdue_milestones=6,
        total_scheduled_milestones=10,
        clearance_pending_days=210,
        days_since_last_update=25,
        dispute_status="NONE",
        delay_remarks="Forest clearance Stage-II and utility shifting pending along elevated corridor",
    ),
    ProjectInput(
        project_id="MOSPI-RTH-0889",
        project_name="Varanasi-Kolkata Greenfield Economic Corridor (Package 2)",
        sector="Road Transport & Highways",
        implementing_agency="NHAI",
        original_cost=3150.0,
        revised_cost=3150.0,
        expenditure=450.0,
        expenditure_change_recent=35.0,
        physical_progress=18.5,
        progress_change_recent=1.6,
        original_duration_months=36.0,
        months_elapsed=12.0,
        current_delay_months=0.0,
        overdue_milestones=1,
        total_scheduled_milestones=9,
        clearance_pending_days=120,
        days_since_last_update=10,
        dispute_status="NONE",
        delay_remarks="Right of way handover progressing; encroachment removal underway",
    ),
    ProjectInput(
        project_id="MOSPI-COAL-0145",
        project_name="North Karanpura Coal Washery and Rail Infrastructure",
        sector="Coal",
        implementing_agency="Central Coalfields Limited (CCL)",
        original_cost=1420.0,
        revised_cost=1780.0,
        expenditure=920.0,
        expenditure_change_recent=20.0,
        physical_progress=58.0,
        progress_change_recent=0.4,
        original_duration_months=42.0,
        months_elapsed=60.0,
        current_delay_months=18.0,
        overdue_milestones=4,
        total_scheduled_milestones=8,
        clearance_pending_days=75,
        days_since_last_update=70,
        dispute_status="TERMINATION_NOTICE",
        delay_remarks="Contractor default notice issued; termination and rebidding under process",
    ),
]
